### ISSUE TITLE
Back test

### ISSUE THREAD

**Issue by altcnews** [jnidzwetzki/crypto-bot#3]
Hi,
Could you please inform how to start backtesting?
Thanks & Regards.

**Comment by jnidzwetzki** [comment]
Hi,

This project is at a very early stage. Therefore most of the code is not well documented and primarily used for my experiments. You will find a good starting point for backtests here: https://github.com/jnidzwetzki/crypto-bot/blob/master/crypto-bot-backtest/src/main/java/com/github/jnidzwetzki/cryptobot/backtest/Main.java

Best Regards
   Jan

**Comment by altcnews** [comment]
Hi,
thank you for your info, i'll start to test it tomorrow.
Great tools anyway.
